types:
  - build
  - test
  - deploy
build:
  script:
    - 'npm install'
    - 'bower install'
    - 'grunt build'
  type: build
  only:
    - /^features/.*$/
  allow_failure: false
#tests:
#  script:
#    - 'npm install'
#    - 'bower install'
#    - 'grunt build'
#    - 'grunt test'
#  type: test
#  allow_failure: false
deploy:
  script:
    - 'npm install'
    - 'bower install'
    - 'grunt build'
    - 'rm -f -r /srv/kcm-latest/*'
    - 'cp -r dist/. /srv/kcm-latest/'
  type: deploy
  only:
    - develop
  allow_failure: false
cache:
  untracked: true
  paths:
  - node_modules/
  - bower_components/
  - dist/