types:
  - build
  - test
  - deploy
build:
  script:
    - 'npm install'
    - 'bower install'
    - 'grunt build'
  type: build
  allow_failure: false
tests:
  script:
    - "grunt test"
  type: test
  allow_failure: false
deploy:
  script:
    - "cp -r dist/* /srv/kcm-latest/"
  type: deploy
  only:
    - develop
  allow_failure: false
cache:
  untracked: true
  paths:
  - node_modules/
  - bower_components/
  - dist/